# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Proyecto1/Zybo-Z7-Master.xdc

# Block Designs: bd/Electric_hook_bd/Electric_hook_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd || ORIG_REF_NAME==Electric_hook_bd} -quiet] -quiet

# IP: bd/Electric_hook_bd/ip/Electric_hook_bd_ram_pull_fish_0_0/Electric_hook_bd_ram_pull_fish_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd_ram_pull_fish_0_0 || ORIG_REF_NAME==Electric_hook_bd_ram_pull_fish_0_0} -quiet] -quiet

# IP: bd/Electric_hook_bd/ip/Electric_hook_bd_axi_traffic_gen_0_0/Electric_hook_bd_axi_traffic_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd_axi_traffic_gen_0_0 || ORIG_REF_NAME==Electric_hook_bd_axi_traffic_gen_0_0} -quiet] -quiet

# IP: bd/Electric_hook_bd/ip/Electric_hook_bd_axi_traffic_gen_1_0/Electric_hook_bd_axi_traffic_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd_axi_traffic_gen_1_0 || ORIG_REF_NAME==Electric_hook_bd_axi_traffic_gen_1_0} -quiet] -quiet

# IP: bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_0/Electric_hook_bd_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd_axi_smc_0 || ORIG_REF_NAME==Electric_hook_bd_axi_smc_0} -quiet] -quiet

# IP: bd/Electric_hook_bd/ip/Electric_hook_bd_clk_wiz_0/Electric_hook_bd_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd_clk_wiz_0 || ORIG_REF_NAME==Electric_hook_bd_clk_wiz_0} -quiet] -quiet

# IP: bd/Electric_hook_bd/ip/Electric_hook_bd_rst_clk_wiz_100M_0/Electric_hook_bd_rst_clk_wiz_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd_rst_clk_wiz_100M_0 || ORIG_REF_NAME==Electric_hook_bd_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_1_0/Electric_hook_bd_axi_smc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd_axi_smc_1_0 || ORIG_REF_NAME==Electric_hook_bd_axi_smc_1_0} -quiet] -quiet

# IP: bd/Electric_hook_bd/ip/Electric_hook_bd_main_0_1/Electric_hook_bd_main_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd_main_0_1 || ORIG_REF_NAME==Electric_hook_bd_main_0_1} -quiet] -quiet

# IP: bd/Electric_hook_bd/ip/Electric_hook_bd_catch_fish_0_0/Electric_hook_bd_catch_fish_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd_catch_fish_0_0 || ORIG_REF_NAME==Electric_hook_bd_catch_fish_0_0} -quiet] -quiet

# IP: bd/Electric_hook_bd/ip/Electric_hook_bd_pull_fish_0_1/Electric_hook_bd_pull_fish_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd_pull_fish_0_1 || ORIG_REF_NAME==Electric_hook_bd_pull_fish_0_1} -quiet] -quiet

# IP: bd/Electric_hook_bd/ip/Electric_hook_bd_vio_0_0/Electric_hook_bd_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd_vio_0_0 || ORIG_REF_NAME==Electric_hook_bd_vio_0_0} -quiet] -quiet

# IP: bd/Electric_hook_bd/ip/Electric_hook_bd_c_accum_0_0/Electric_hook_bd_c_accum_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd_c_accum_0_0 || ORIG_REF_NAME==Electric_hook_bd_c_accum_0_0} -quiet] -quiet

# IP: bd/Electric_hook_bd/ip/Electric_hook_bd_xlconstant_0_0/Electric_hook_bd_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd_xlconstant_0_0 || ORIG_REF_NAME==Electric_hook_bd_xlconstant_0_0} -quiet] -quiet

# IP: bd/Electric_hook_bd/ip/Electric_hook_bd_puntaje_0_0/Electric_hook_bd_puntaje_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd_puntaje_0_0 || ORIG_REF_NAME==Electric_hook_bd_puntaje_0_0} -quiet] -quiet

# IP: bd/Electric_hook_bd/ip/Electric_hook_bd_axi_traffic_gen_2_0/Electric_hook_bd_axi_traffic_gen_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd_axi_traffic_gen_2_0 || ORIG_REF_NAME==Electric_hook_bd_axi_traffic_gen_2_0} -quiet] -quiet

# IP: bd/Electric_hook_bd/ip/Electric_hook_bd_ila_0_0/Electric_hook_bd_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd_ila_0_0 || ORIG_REF_NAME==Electric_hook_bd_ila_0_0} -quiet] -quiet

# IP: bd/Electric_hook_bd/ip/Electric_hook_bd_ila_1_0/Electric_hook_bd_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd_ila_1_0 || ORIG_REF_NAME==Electric_hook_bd_ila_1_0} -quiet] -quiet

# IP: bd/Electric_hook_bd/ip/Electric_hook_bd_ila_2_0/Electric_hook_bd_ila_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Electric_hook_bd_ila_2_0 || ORIG_REF_NAME==Electric_hook_bd_ila_2_0} -quiet] -quiet

# XDC: bd/Electric_hook_bd/Electric_hook_bd_ooc.xdc
