# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.runs/synth_1/Electric_hook_bd_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.2 [current_project]
set_property ip_repo_paths {
  {c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto1/ip_repo/puntaje_1.0}
  {c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/Ip_cores}
} [current_project]
update_ip_catalog
set_property ip_output_repo {c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files {{C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/Ip_cores/coe_files_pull_fish/data.coe}}
add_files {{C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/Ip_cores/coe_files_pull_fish/addr.coe}}
add_files {{C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/Ip_cores/coe_files_pull_fish/mask.coe}}
add_files {{C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/Ip_cores/coe_files_pull_fish/ctrl.coe}}
add_files {{C:/Users/Gabriela Rivera/Downloads/COE/COE_FILES/data.coe}}
add_files {{C:/Users/Gabriela Rivera/Downloads/COE/COE_FILES/addr.coe}}
add_files {{C:/Users/Gabriela Rivera/Downloads/COE/COE_FILES/mask.coe}}
add_files {{C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto1/Proyecto_1/Ip_cores/coe_test_mode/COE_FILES/ctrl.coe}}
add_files {{C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto1/Proyecto_1/Ip_cores/coe_test_mode/COE_FILES/data.coe}}
add_files {{C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto1/Proyecto_1/Ip_cores/coe_test_mode/COE_FILES/addr.coe}}
add_files {{C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto1/Proyecto_1/Ip_cores/coe_test_mode/COE_FILES/mask.coe}}
add_files {{C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/Ip_cores/coe_test_mode/COE_FILES/data.coe}}
add_files {{C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/Ip_cores/coe_test_mode/COE_FILES/addr.coe}}
add_files {{C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/Ip_cores/coe_test_mode/COE_FILES/mask.coe}}
add_files {{C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/Ip_cores/coe_test_mode/COE_FILES/ctrl.coe}}
read_vhdl -library xil_defaultlib {{C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/hdl/Electric_hook_bd_wrapper.vhd}}
add_files {{C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/Electric_hook_bd.bd}}
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_traffic_gen_0_0/Electric_hook_bd_axi_traffic_gen_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_traffic_gen_1_0/Electric_hook_bd_axi_traffic_gen_1_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_traffic_gen_1_0/Electric_hook_bd_axi_traffic_gen_1_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_0/bd_0/ip/ip_1/bd_9987_psr_aclk_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_0/bd_0/ip/ip_1/bd_9987_psr_aclk_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_0/bd_0/ip/ip_5/bd_9987_s00a2s_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_0/bd_0/ip/ip_6/bd_9987_sarn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_0/bd_0/ip/ip_7/bd_9987_srn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_0/bd_0/ip/ip_8/bd_9987_sawn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_0/bd_0/ip/ip_9/bd_9987_swn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_0/bd_0/ip/ip_10/bd_9987_sbn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_0/bd_0/ip/ip_11/bd_9987_m00s2a_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_0/ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_clk_wiz_0/Electric_hook_bd_clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_clk_wiz_0/Electric_hook_bd_clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_clk_wiz_0/Electric_hook_bd_clk_wiz_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_rst_clk_wiz_100M_0/Electric_hook_bd_rst_clk_wiz_100M_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_rst_clk_wiz_100M_0/Electric_hook_bd_rst_clk_wiz_100M_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_rst_clk_wiz_100M_0/Electric_hook_bd_rst_clk_wiz_100M_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_1_0/bd_0/ip/ip_1/bd_becb_psr_aclk_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_1_0/bd_0/ip/ip_1/bd_becb_psr_aclk_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_1_0/bd_0/ip/ip_5/bd_becb_s00a2s_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_1_0/bd_0/ip/ip_6/bd_becb_sarn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_1_0/bd_0/ip/ip_7/bd_becb_srn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_1_0/bd_0/ip/ip_8/bd_becb_sawn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_1_0/bd_0/ip/ip_9/bd_becb_swn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_1_0/bd_0/ip/ip_10/bd_becb_sbn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_1_0/bd_0/ip/ip_11/bd_becb_m00s2a_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_smc_1_0/ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_vio_0_0/Electric_hook_bd_vio_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_vio_0_0/Electric_hook_bd_vio_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_c_accum_0_0/Electric_hook_bd_c_accum_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_traffic_gen_2_0/Electric_hook_bd_axi_traffic_gen_2_0_ooc.xdc}}]
set_property used_in_synthesis false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_ila_0_0/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_ila_0_0/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_ila_0_0/ila_v6_2/constraints/ila.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_ila_0_0/Electric_hook_bd_ila_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/Electric_hook_bd_ooc.xdc}}]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/constrs_1/imports/Proyecto1/Zybo-Z7-Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto_1/electric_hook/electric_hook.srcs/constrs_1/imports/Proyecto1/Zybo-Z7-Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Electric_hook_bd_wrapper -part xc7z010clg400-1
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Electric_hook_bd_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Electric_hook_bd_wrapper_utilization_synth.rpt -pb Electric_hook_bd_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
