# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_traffic_gen_2_0/Electric_hook_bd_axi_traffic_gen_2_0.xci
# IP: The module: 'Electric_hook_bd_axi_traffic_gen_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_traffic_gen_2_0/Electric_hook_bd_axi_traffic_gen_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Electric_hook_bd_axi_traffic_gen_2_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_traffic_gen_2_0/Electric_hook_bd_axi_traffic_gen_2_0.xci
# IP: The module: 'Electric_hook_bd_axi_traffic_gen_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Gabriela Rivera/OneDrive/Escritorio/Proyecto1/electric_hook/electric_hook.srcs/sources_1/bd/Electric_hook_bd/ip/Electric_hook_bd_axi_traffic_gen_2_0/Electric_hook_bd_axi_traffic_gen_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Electric_hook_bd_axi_traffic_gen_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
