# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Proyecto1/Zybo-Z7-Master.xdc

# Block Designs: bd/design_electric_hook/design_electric_hook.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_electric_hook || ORIG_REF_NAME==design_electric_hook} -quiet] -quiet

# IP: bd/design_electric_hook/ip/design_electric_hook_axi_traffic_gen_0_0/design_electric_hook_axi_traffic_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_electric_hook_axi_traffic_gen_0_0 || ORIG_REF_NAME==design_electric_hook_axi_traffic_gen_0_0} -quiet] -quiet

# IP: bd/design_electric_hook/ip/design_electric_hook_axi_traffic_gen_1_0/design_electric_hook_axi_traffic_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_electric_hook_axi_traffic_gen_1_0 || ORIG_REF_NAME==design_electric_hook_axi_traffic_gen_1_0} -quiet] -quiet

# IP: bd/design_electric_hook/ip/design_electric_hook_ram_pull_fish_0_0/design_electric_hook_ram_pull_fish_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_electric_hook_ram_pull_fish_0_0 || ORIG_REF_NAME==design_electric_hook_ram_pull_fish_0_0} -quiet] -quiet

# IP: bd/design_electric_hook/ip/design_electric_hook_axi_smc_0/design_electric_hook_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_electric_hook_axi_smc_0 || ORIG_REF_NAME==design_electric_hook_axi_smc_0} -quiet] -quiet

# IP: bd/design_electric_hook/ip/design_electric_hook_clk_wiz_0/design_electric_hook_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_electric_hook_clk_wiz_0 || ORIG_REF_NAME==design_electric_hook_clk_wiz_0} -quiet] -quiet

# IP: bd/design_electric_hook/ip/design_electric_hook_rst_clk_wiz_100M_0/design_electric_hook_rst_clk_wiz_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_electric_hook_rst_clk_wiz_100M_0 || ORIG_REF_NAME==design_electric_hook_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/design_electric_hook/ip/design_electric_hook_axi_smc_1_0/design_electric_hook_axi_smc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_electric_hook_axi_smc_1_0 || ORIG_REF_NAME==design_electric_hook_axi_smc_1_0} -quiet] -quiet

# IP: bd/design_electric_hook/ip/design_electric_hook_main_0_0/design_electric_hook_main_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_electric_hook_main_0_0 || ORIG_REF_NAME==design_electric_hook_main_0_0} -quiet] -quiet

# IP: bd/design_electric_hook/ip/design_electric_hook_catch_fish_0_0/design_electric_hook_catch_fish_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_electric_hook_catch_fish_0_0 || ORIG_REF_NAME==design_electric_hook_catch_fish_0_0} -quiet] -quiet

# IP: bd/design_electric_hook/ip/design_electric_hook_pull_fish_0_0/design_electric_hook_pull_fish_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_electric_hook_pull_fish_0_0 || ORIG_REF_NAME==design_electric_hook_pull_fish_0_0} -quiet] -quiet

# IP: bd/design_electric_hook/ip/design_electric_hook_xlconstant_0_0/design_electric_hook_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_electric_hook_xlconstant_0_0 || ORIG_REF_NAME==design_electric_hook_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_electric_hook/ip/design_electric_hook_ila_0_0/design_electric_hook_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_electric_hook_ila_0_0 || ORIG_REF_NAME==design_electric_hook_ila_0_0} -quiet] -quiet

# IP: bd/design_electric_hook/ip/design_electric_hook_vio_0_0/design_electric_hook_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_electric_hook_vio_0_0 || ORIG_REF_NAME==design_electric_hook_vio_0_0} -quiet] -quiet

# XDC: bd/design_electric_hook/design_electric_hook_ooc.xdc
